on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      outputDirName:
        required: false
        type: string

jobs:
  build_win:
    runs-on: ${{inputs.platform}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
  # Go Setup
      - name: Setup Go
        uses: actions/checkout@v2
  # Build
      - name: Install Deps
        run: |
          mkdir out
          cd out
          go build ..
          cd ..

      - name: Bundle
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.outputDirName}}
          path: "./out"