# Stolen from https://medium.com/swlh/setting-up-github-actions-for-go-project-ea84f4ed3a40
name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux:
    name: Build the Tool for Linux
    uses: ../actions/build.yaml
    with:
      platform: ubuntu-latest
      outputDirName: "edpvp-log-prepare-linux"
